# 基础镜像
FROM python:3.8-alpine

# Qiandao
WORKDIR /usr/src/app

# Environments
ENV PYCURL_SSL_LIBRARY=openssl
RUN apk update && \
  apk add --no-cache libcurl && \
  apk add --no-cache --virtual .build-deps git curl-dev build-base && \
  git clone --depth 1 https://github.com/qiandao-today/qiandao.git . && \
  sed -i '/==/!d' requirements.txt && \
  sed -i 's/# //' requirements.txt && \
  sed -i '/ddddocr/d' requirements.txt && \
  sed -i '/opencv-python/d' requirements.txt && \
  pip install --no-cache-dir -r requirements.txt && \
  rm -rf .git && \
  apk --purge del .build-deps

ENV PORT 8923
EXPOSE $PORT/tcp

# timezone
ENV TZ=CST-8

# 添加挂载点
VOLUME ["/usr/src/app/"]

CMD ["python","/usr/src/app/run.py"]