# 基础镜像
FROM python:3.9-alpine

# Qiandao
WORKDIR /usr/src/app

# Environments
ENV PYCURL_SSL_LIBRARY=openssl

RUN apk update && \
  apk add --no-cache libcurl && \
  apk add --no-cache --virtual .build-deps build-base curl-dev git && \
  git clone --depth 1 https://github.com/qd-today/qd.git . && \
  sed -i '/^-i.*/d' requirements.txt && \
  sed -i 's/^# pycurl/pycurl/' requirements.txt && \
  pip install --no-cache-dir -r requirements.txt && \
  apk --purge del .build-deps && \
  rm -rf .git && \
  rm -rf /var/cache/apk/*

ENV PORT 80
EXPOSE $PORT/tcp

# timezone
ENV TZ=CST-8

# 添加挂载点
VOLUME ["/usr/src/app/config"]

CMD ["python","/usr/src/app/run.py"]