version: "3"

services:
  qiandao:
    image: hicasper/qiandao-today:latest
    depends_on:
      - redis
    ports:
      - "8923:80"
    environment:
      # PORT: 80
      # DB_TYPE: mysql
      # JAWSDB_MARIA_URL: 'mysql://user:pass@localhost:3306/dbname?auth_plugin='
      REDISCLOUD_URL: 'redis://redis:6379'
      # MAIL_SMTP:
      # MAIL_PORT:
      # MAIL_USER:
      # MAIL_PASSWORD:

  redis:
    image: redis:6-alpine
    command: ["--loglevel warning"]
    volumes:
      - /data