name: Build Docker Image

on:
  push:
    branches:
      - 'autobuild'
  schedule:
    - cron: "0 18 */7 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      - 
        name: Get upstream version
        id: getversion
        run: |
          echo "GITVERSION=$(curl -fsSL https://github.com/qd-today/qd/raw/master/version.json | jq '.version')" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qd-today:latest,${{ secrets.DOCKERHUB_USERNAME }}/qd-today:${{ steps.getversion.outputs.GITVERSION }}

  build-lite:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      - 
        name: Get upstream version
        id: getversion
        run: |
          echo "GITVERSION=$(curl -fsSL https://github.com/qd-today/qd/raw/master/version.json | jq '.version')" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile-lite
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qd-today:lite,${{ secrets.DOCKERHUB_USERNAME }}/qd-today:${{ steps.getversion.outputs.GITVERSION }}-lite
