name: Build Docker Image

on:
  push:
    branches:
      - 'autobuild'
  schedule:
    - cron: "0 18 */3 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
      - 
        name: Get version
        id: get-version
        if: startsWith(github.ref, 'refs/tags/') && startsWith(github.repository, 'qiandao-today/qiandao')
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: hicasper/qiandao-today:latest,hicasper/qiandao-today:${{ steps.get_version.outputs.VERSION }}

  build-lite:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
      - 
        name: Get version
        id: get-version
        if: startsWith(github.ref, 'refs/tags/') && startsWith(github.repository, 'qiandao-today/qiandao')
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile-lite
          push: true
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v7
          tags: hicasper/qiandao-today:lite,hicasper/qiandao-today:${{ steps.get_version.outputs.VERSION }}-lite